#!/usr/bin/env python3
"""gen_marketplace.py — generate .claude-plugin/marketplace.json (A8 §4.7, QA-04).

The marketplace manifest is GENERATED from each skill's `metadata.plugin`
frontmatter — never hand-maintained (no duplication; a skill's bundle membership
lives in exactly one place, its own SKILL.md). Each distinct `metadata.plugin`
value becomes one plugin entry whose `skills` list is the folders that name it.

  --check   regenerate in memory and DIFF against the on-disk manifest; exit
            nonzero on drift (the CI gate — research §4.7).
  --write   rewrite the on-disk manifest from the skills.

Stdlib + pyyaml only. Reuses the S2 main(argv)->int contract.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

SCRIPTS = Path(__file__).resolve().parent
REPO = SCRIPTS.parent
MANIFEST = REPO / ".claude-plugin" / "marketplace.json"

# The stable manifest header (everything except the generated `plugins` array).
_HEADER = {
    "$schema": "https://json.schemastore.org/claude-code-marketplace.json",
    "_comment": "GENERATED by scripts/gen_marketplace.py — do not edit by hand",
    "name": "hse-leadership-skills",
    "description": "HSE Leadership Skills — consultant-grade health, safety & environment artifact tools",
    "owner": {"name": "Eyekyam", "email": "ashley@eyekyam.com"},
}

_FM_RE = re.compile(r"^---\n(.*?)\n---\n", re.S)


def _frontmatter(skill_md: Path) -> Dict[str, Any]:
    m = _FM_RE.match(skill_md.read_text(encoding="utf-8"))
    if not m:
        return {}
    try:
        return yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        return {}


def _iter_skills(repo: Path) -> List[Path]:
    """Every shipped skill folder (skills/ — the examples/ proof stubs are NOT
    marketplace plugins)."""
    root = repo / "skills"
    if not root.is_dir():
        return []
    return sorted(child.parent for child in root.rglob("SKILL.md"))


def build_manifest(repo: Path = REPO) -> Dict[str, Any]:
    """Build the manifest dict from every skill's metadata.plugin."""
    bundles: Dict[str, List[str]] = {}
    for skill_dir in _iter_skills(repo):
        fm = _frontmatter(skill_dir / "SKILL.md")
        meta = fm.get("metadata") or {}
        plugin = meta.get("plugin")
        if not plugin:
            continue
        bundles.setdefault(plugin, []).append(skill_dir.name)
        # D-06 cross-bundle membership: a skill owned by one bundle (metadata.plugin)
        # may also appear in others via metadata.bundled_in. The manifest stays derived
        # from frontmatter alone (no second source of truth) — WR-05. rule-6 validates
        # each bundled_in value is a registered bundle at lint time.
        for extra in (meta.get("bundled_in") or []):
            bundles.setdefault(extra, []).append(skill_dir.name)

    plugins: List[Dict[str, Any]] = []
    for name in sorted(bundles):
        plugins.append({"name": name, "skills": sorted(bundles[name])})

    manifest = dict(_HEADER)
    manifest["plugins"] = plugins
    return manifest


def _serialize(manifest: Dict[str, Any]) -> str:
    return json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(description="Generate/check marketplace.json (A8 §4.7).")
    g = p.add_mutually_exclusive_group()
    g.add_argument("--check", action="store_true",
                   help="diff the generated manifest against disk; nonzero on drift")
    g.add_argument("--write", action="store_true", help="rewrite marketplace.json")
    p.add_argument("--repo", default=str(REPO), help="repo root (default: inferred)")
    args = p.parse_args(argv)
    repo = Path(args.repo).resolve()
    manifest_path = repo / ".claude-plugin" / "marketplace.json"

    generated = _serialize(build_manifest(repo))

    if args.write:
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        manifest_path.write_text(generated, encoding="utf-8")
        print(f"WROTE {manifest_path}")
        return 0

    # --check (default): compare against disk.
    on_disk = manifest_path.read_text(encoding="utf-8") if manifest_path.is_file() else ""
    if on_disk == generated:
        print("OK: marketplace.json in sync with skill metadata.plugin")
        return 0

    print("DRIFT: marketplace.json is stale; run `gen_marketplace.py --write`", file=sys.stderr)
    # A compact, line-level hint of what differs.
    import difflib
    diff = difflib.unified_diff(
        on_disk.splitlines(), generated.splitlines(),
        fromfile="marketplace.json (on disk)", tofile="generated", lineterm="",
    )
    for line in diff:
        print(line, file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
